#!/usr/bin/env node
/**
 * Pre-selects 20 puzzles with hints from the full solution set
 * and writes them to src/generatedPuzzles.ts so the data/ folder
 * is not needed in the production bundle.
 *
 * Run: node scripts/generate_print_puzzles.js
 */

const fs = require('fs');
const path = require('path');

const allPuzzles = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'data', 'magic_squares_16_distinct.json'), 'utf-8')
);

function noConflicts(positions) {
  for (let i = 0; i < positions.length; i++) {
    for (let j = i + 1; j < positions.length; j++) {
      const [r1, c1] = positions[i];
      const [r2, c2] = positions[j];
      if (r1 === r2 || c1 === c2) return false;
      if (r1 - c1 === r2 - c2) return false;
      if (r1 + c1 === r2 + c2) return false;
    }
  }
  return true;
}

// Pre-compute valid hint layouts
const HINT_LAYOUTS_2 = [];
const HINT_LAYOUTS_3 = [];

const all = [];
for (let r = 0; r < 4; r++)
  for (let c = 0; c < 4; c++)
    all.push([r, c]);

for (let i = 0; i < all.length; i++)
  for (let j = i + 1; j < all.length; j++) {
    const combo = [all[i], all[j]];
    if (noConflicts(combo)) HINT_LAYOUTS_2.push(combo);
  }

for (let i = 0; i < all.length; i++)
  for (let j = i + 1; j < all.length; j++)
    for (let k = j + 1; k < all.length; k++) {
      const combo = [all[i], all[j], all[k]];
      if (noConflicts(combo)) HINT_LAYOUTS_3.push(combo);
    }

// Deterministic seeded shuffle (Mulberry32 PRNG)
function seededShuffle(arr, seed) {
  const out = [...arr];
  let s = seed | 0;
  function rand() {
    s = (s + 0x6D2B79F5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function findDistinctHints(grid, layouts, seed) {
  const valid = layouts.filter(layout => {
    const values = layout.map(([r, c]) => grid[r][c]);
    return new Set(values).size === values.length;
  });
  if (valid.length === 0) return layouts[0];
  const shuffled = seededShuffle(valid, seed);
  return shuffled[0];
}

function selectPuzzles() {
  const hardPool = allPuzzles.filter(g => new Set(g.flat()).size <= 4);
  const easyPool = allPuzzles.filter(g => new Set(g.flat()).size > 6);

  const hardShuffled = seededShuffle(hardPool, 42);
  const easyShuffled = seededShuffle(easyPool, 137);

  const hardPicks = hardShuffled.slice(0, 10);
  const easyPicks = easyShuffled.slice(0, 10);

  const puzzles = [];
  let h2idx = 0;
  let h3idx = 0;

  for (let i = 0; i < 20; i++) {
    if (i % 2 === 0 && h3idx < easyPicks.length) {
      const grid = easyPicks[h3idx];
      const hints = findDistinctHints(grid, HINT_LAYOUTS_3, i * 31 + 7);
      puzzles.push({ grid, hints });
      h3idx++;
    } else if (h2idx < hardPicks.length) {
      const grid = hardPicks[h2idx];
      const hints = findDistinctHints(grid, HINT_LAYOUTS_2, i * 31 + 13);
      puzzles.push({ grid, hints });
      h2idx++;
    } else if (h3idx < easyPicks.length) {
      const grid = easyPicks[h3idx];
      const hints = findDistinctHints(grid, HINT_LAYOUTS_3, i * 31 + 7);
      puzzles.push({ grid, hints });
      h3idx++;
    }
  }

  return puzzles;
}

const puzzles = selectPuzzles();

const output = `// Auto-generated by scripts/generate_print_puzzles.js — do not edit manually.
// Re-generate: node scripts/generate_print_puzzles.js

export interface PrintPuzzle {
  grid: number[][];
  hints: [number, number][];
}

export const PUZZLES: PrintPuzzle[] = ${JSON.stringify(puzzles, null, 2)};
`;

const outPath = path.join(__dirname, '..', 'src', 'generatedPuzzles.ts');
fs.writeFileSync(outPath, output);
console.log(`Wrote ${puzzles.length} puzzles to ${outPath}`);
