#!/usr/bin/env node
/**
 * Pre-selects ~50 puzzles with hints from the full solution set
 * and writes them to src/generatedPuzzles.ts so the data/ folder
 * is not needed in the production bundle.
 *
 * Run: node scripts/generate_print_puzzles.cjs
 */

const fs = require('fs');
const path = require('path');

const allPuzzles = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'data', 'magic_squares_16_distinct.json'), 'utf-8')
);

function noConflicts(positions) {
  for (let i = 0; i < positions.length; i++) {
    for (let j = i + 1; j < positions.length; j++) {
      const [r1, c1] = positions[i];
      const [r2, c2] = positions[j];
      if (r1 === r2 || c1 === c2) return false;
      if (r1 - c1 === r2 - c2) return false;
      if (r1 + c1 === r2 + c2) return false;
    }
  }
  return true;
}

// Pre-compute valid hint layouts
const HINT_LAYOUTS_2 = [];
const HINT_LAYOUTS_3 = [];

const all = [];
for (let r = 0; r < 4; r++)
  for (let c = 0; c < 4; c++)
    all.push([r, c]);

for (let i = 0; i < all.length; i++)
  for (let j = i + 1; j < all.length; j++) {
    const combo = [all[i], all[j]];
    if (noConflicts(combo)) HINT_LAYOUTS_2.push(combo);
  }

for (let i = 0; i < all.length; i++)
  for (let j = i + 1; j < all.length; j++)
    for (let k = j + 1; k < all.length; k++) {
      const combo = [all[i], all[j], all[k]];
      if (noConflicts(combo)) HINT_LAYOUTS_3.push(combo);
    }

// Deterministic seeded shuffle (Mulberry32 PRNG)
function seededShuffle(arr, seed) {
  const out = [...arr];
  let s = seed | 0;
  function rand() {
    s = (s + 0x6D2B79F5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function findDistinctHints(grid, layouts, seed) {
  const valid = layouts.filter(layout => {
    const values = layout.map(([r, c]) => grid[r][c]);
    return new Set(values).size === values.length;
  });
  if (valid.length === 0) return layouts[0];
  const shuffled = seededShuffle(valid, seed);
  return shuffled[0];
}

function selectPuzzles() {
  // Pool by unique value count
  const pool7 = allPuzzles.filter(g => new Set(g.flat()).size === 7);   // 12 available
  const pool8 = allPuzzles.filter(g => new Set(g.flat()).size === 8);   // 144 available
  const pool9 = allPuzzles.filter(g => new Set(g.flat()).size === 9);   // 2 available

  // Shuffle each pool
  const shuffled7 = seededShuffle(pool7, 42);
  const shuffled8 = seededShuffle(pool8, 137);
  const shuffled9 = seededShuffle(pool9, 73);

  // Hard: 5 from 7-unique, 1 from 9-unique (2 hints each)
  const hardPicks7 = shuffled7.slice(0, 5);
  const hardPicks9 = shuffled9.slice(0, 1);

  // Normal: 44 from 8-unique (3 hints each)
  const normalPicks = shuffled8.slice(0, 44);

  const puzzles = [];

  // Add hard puzzles (7-unique) with 3 hints + required values
  for (let i = 0; i < hardPicks7.length; i++) {
    const grid = hardPicks7[i];
    const hints = findDistinctHints(grid, HINT_LAYOUTS_3, i * 31 + 13);
    const uniqueValues = [...new Set(grid.flat())].sort((a, b) => a - b);
    puzzles.push({ grid, hints, hard: true, uniqueValues });
  }

  // Add hard puzzle (9-unique) with 3 hints + required values
  for (let i = 0; i < hardPicks9.length; i++) {
    const grid = hardPicks9[i];
    const hints = findDistinctHints(grid, HINT_LAYOUTS_3, i * 31 + 97);
    const uniqueValues = [...new Set(grid.flat())].sort((a, b) => a - b);
    puzzles.push({ grid, hints, hard: true, uniqueValues });
  }

  // Add normal puzzles (8-unique) with 3 hints
  for (let i = 0; i < normalPicks.length; i++) {
    const grid = normalPicks[i];
    const hints = findDistinctHints(grid, HINT_LAYOUTS_3, i * 31 + 7);
    puzzles.push({ grid, hints, hard: false });
  }

  // Interleave: spread hard puzzles throughout
  // Place hard puzzles at roughly even intervals
  const hard = puzzles.filter(p => p.hard);
  const normal = puzzles.filter(p => !p.hard);
  const result = [];
  const interval = Math.floor(normal.length / (hard.length + 1));

  let hi = 0;
  for (let i = 0; i < normal.length; i++) {
    result.push(normal[i]);
    if (hi < hard.length && (i + 1) % interval === 0) {
      result.push(hard[hi]);
      hi++;
    }
  }
  // Append any remaining hard puzzles
  while (hi < hard.length) {
    result.push(hard[hi]);
    hi++;
  }

  return result;
}

const puzzles = selectPuzzles();

const output = `// Auto-generated by scripts/generate_print_puzzles.cjs — do not edit manually.
// Re-generate: npm run generate:puzzles

export interface PrintPuzzle {
  grid: number[][];
  hints: [number, number][];
  hard: boolean;
  uniqueValues?: number[];
}

export const PUZZLES: PrintPuzzle[] = ${JSON.stringify(puzzles, null, 2)};
`;

const outPath = path.join(__dirname, '..', 'src', 'generatedPuzzles.ts');
fs.writeFileSync(outPath, output);

const hardCount = puzzles.filter(p => p.hard).length;
const normalCount = puzzles.filter(p => !p.hard).length;
console.log(`Wrote ${puzzles.length} puzzles (${hardCount} hard, ${normalCount} normal) to ${outPath}`);
